config/routes.rb
Shelftalkers::Application.routes.draw do
  
  resources :talkers

  resources :talkers do
    collection do
      get 'print'
    end
  end

  match '/print' => 'talkers#print'
  match '/login' => 'talkers#login'
  match '/submit' => 'talkers#submit'

  root :to => "talkers#index"

end

app/models/talker.rb
class Talker < ActiveRecord::Base
  attr_accessible :blurb, :producer, :product
  validates :producer, :product, :blurb, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/talkers_controller.rb
class TalkersController < ApplicationController

  if File.file?('constants.rb')
    require_relative 'constants'
  else
    USER_ID, PASSWORD = 'admin', 'test'
  end

  before_filter :authenticate, :only => [ :edit, :destroy, :new, :update, :create, :login] 
  # GET /talkers
  # GET /talkers.jsonk

  def submit
    button_redirect
  end

  def button_redirect
    if params[:commit] == "Print selected talkers"
      params[:commit] = ""
      session[:checked] = nil
      redirect_to(print_path(:checked => params[:checked], :format => 'pdf')) and return
    elsif params[:commit] == "Delete selected talkers"
      session[:checked] = nil
      params[:commit] = ""
      if not params[:checked].nil?
        @num_talkers = params[:checked].length
        Talker.where(:id => params[:checked].keys).delete_all
        params[:checked] = nil
        redirect_to talkers_path, notice: "Talkers successfully deleted." and return
      else
        redirect_to talkers_path, notice: "No talkers selected; no talkers deleted." and return
      end
    elsif params[:commit] == "New talker"
      redirect_to new_talker_path and return
    elsif params[:login] == ""
      redirect_to login_path and return
    elsif not params['edit'].nil?
      redirect_to edit_talker_path(params['edit'].keys[0]) and return
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @talkers }
    end
  end
 
  def index
    @talkers = Talker.order("producer, product")
    @checked = session[:checked].nil? ? [] : Talker.find(session[:checked].keys)
    session[:checked] = params[:checked]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @talkers }
    end
  end

  # GET /talkers/1
  # GET /talkers/1.json
  def login
    redirect_to talkers_path and return
  end

  def print
#    prawnto :prawn => { :top_margin => 75 }
    @talkers = params[:checked].nil? ? Talker.all(:order => "producer, product") : Talker.find(params[:checked].keys, :order => "producer, product")
#    @talkerpairs = @talkers.each_slice(2).to_a
    respond_to do |format|
      format.html
      format.xml { render :xml => @talkers }
      format.pdf { render :layout => false }
    end
#@pdf = PDFKit.new(print_path({:checked => params[:checked]}))
#send_data(@pdf.to_pdf, :filename =>"some.pdf", :type => "application/pdf")
#send_data(@pdf.to_pdf, :filename => "some_name.pdf", :type => 'application/pdf')
    #@checked = params[:checked].nil? ? Talker.all : Talker.find(params[:checked].keys)
  end

  def show
    @talker = Talker.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @talker }
      format.pdf { redirect_to print_path(:checked => {params[:id] => 1}, :format => params[:format])}
    end
  end

  # GET /talkers/new
  # GET /talkers/new.json
  def new
    @title = "New talker"
    @talker = Talker.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @talker }
    end
  end

  # GET /talkers/1/edit
  def edit
    @title = "Edit talker"
    @talker = Talker.find(params[:id])
  end

  # POST /talkers
  # POST /talkers.json
  
  def create
    @talker = Talker.new(params[:talker])

    respond_to do |format|
      if @talker.save
        format.html { redirect_to talkers_path(:anchor => "checked_#{@talker.id}"), notice: 'Talker was successfully created.' }
        format.json { render json: @talker, status: :created, location: @talker }
      else
        format.html { render action: "new" }
        format.json { render json: @talker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /talkers/1
  # PUT /talkers/1.json
  def update
    @talker = Talker.find(params[:id])

    respond_to do |format|
      if @talker.update_attributes(params[:talker])
        format.html { redirect_to talkers_path(:anchor => "checked_#{@talker.id}"), notice: 'Talker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @talker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talkers/1
  # DELETE /talkers/1.json
  def destroy
    @talker = Talker.find(params[:id])
    @talker.destroy

    respond_to do |format|
      format.html { redirect_to talkers_url, notice: 'Talker successfully deleted' }
      format.json { head :no_content }
    end
  end

  protected
    def authenticate
      authenticate_or_request_with_http_basic do |id, password|
        id == USER_ID && password == PASSWORD && session[:logged_in] = true
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/talkers_helper.rb
module TalkersHelper

def icon(name, size=1)
    #icon("camera-retro")
    #<i class="icon-camera-retro"></i> 
    
    html = "<i class='icon-#{name}' "
    html += "style='font-size:#{size}em' "
    html += "></i>"
    html.html_safe
  end
  
  def button_icon(text, url, name, size=1.5, *options)
    #button_icon("Camera Retro button", "#","refresh",1)
    #<a class="button refresh" href="#"><i style="font-size:1.5em" class="icon-refresh"></i> Camera Retro button</a>
    class_to_add = "button #{name}"
    options.each { |opt| class_to_add += " #{opt}" } if !options.empty?
    link_to(url, html_options = { :class => class_to_add }) {icon(name, 1.5) + " " + text}
  end
  
  def link_icon(text, url, name, size=1, *options)
    #link_icon("Camera Retro button", "#","refresh",1)
    # <a class="refresh" href="#"><i style="font-size:1.5em" class="icon-refresh"></i> Camera Retro button</a>
    
    class_to_add = "#{name}"
    options.each { |opt| class_to_add += " #{opt}" } if !options.empty?
    link_to(url, html_options = { :class => class_to_add }) {icon(name, size) + " " + text}
  end
end

app/views/home/index.html.haml
%h1 Hello there
%h2= link_to "Add talker", talkers_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Shelf Talkers 
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    .header
      .title-box
        %span.company Company Name
        %span.title Shelf Talkers
    #main
      .container-fluid
        - if flash[:notice]
          #notice.message= flash[:notice]
        - elsif flash[:warning]
          #warning.message= flash[:warning]
        = yield

app/views/talkers/_form.html.erb
<div class="formbody">
<%= form_for(@talker) do |f| %>
  <% if @talker.errors.any? %>
    <div class = "alert alert-error">
      <%= pluralize(@talker.errors.count, "error") %> prevented this talker from being saved:

      <ul>
      <% @talker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset> 
    <legend><%= @title%></legend>
      <%= f.label :producer %>
      <%= f.text_field :producer, :class => "input-xlarge" %>
      <%= f.label :product %>
      <%= f.text_field :product, :class => "input-xlarge"  %>
      <%= f.label :blurb %>
      <%= f.text_area :blurb, :class => "input-xlarge", :rows => "7" %>
    <div class="form-actions">
      <%= f.submit :class => "btn btn-primary"%>
      <%= link_to 'Cancel', talkers_path(@talker.nil? ? nil : :anchor => "checked_"+@talker.id.to_s), :class => "btn" %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/talkers/edit.html.erb
<%= render 'form' %>

app/views/talkers/index.html.haml
= form_tag submit_path, :method => :get do
  %table.table-talkers
    %thead
      %tr
        %th= params['show']
        %th
        %th
        -if session[:logged_in] 
          %th
    %tbody
      - @talkers.each do |talker|
        %tr
          %td= check_box_tag "checked[#{talker.id}]", 1, @checked.include?(talker) ? "checked" : false
          %td
            %div.producer= talker.producer
          %td
            %div.product= talker.product
            %div.blurb= talker.blurb
          -if session[:logged_in]
            %td
              %button.btn-link{:name => "edit["+talker.id.to_s+"]"}
                Edit
      .footer
        .footer-content
          = submit_tag 'Print selected talkers', :class => 'btn btn-success'
          -if session[:logged_in]
            = submit_tag "Delete selected talkers", :class => 'btn btn-menu', data: { confirm: 'Are you sure you want to delete the selected talkers?' }
            = submit_tag "New talker", :class => 'btn btn-menu'
          -else
            %button.btn.btn-menu{:name => 'login'}
              Admin

app/views/talkers/new.html.erb
<%= render 'form' %>

app/views/talkers/print.html.haml
%table
  - @talkerpairs.each do |talkerpair|
    %tr
      - talkerpair.each do |talker|
        %td
          %table.pdf
            %thead
              %tr 
                %th fold
            %tbody
              %tr
                %td.producer= talker.producer
              %tr
                %td.product= talker.product
              %tr
                %td= talker.blurb

= link_to("PDF", print_path(:checked => params[:checked], :format => :pdf))

app/views/talkers/show.html.haml
%h4= @talker.producer
%h3= @talker.product
%p= @talker.blurb

= link_to 'PDF', params.merge(:format => :pdf)
= link_to 'Back', talkers_path
= link_to 'Edit', edit_talker_path(@talker)